; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
; Emanuel Dêvid Paulino Felix - 469870
    
#include "p18f4550.inc"
    
CONFIG FOSC = XT_XT
CONFIG WDT = OFF
CONFIG LVP = OFF

VARIAVEIS UDATA_ACS 0 ; DEFININDO VARIÁVEIS
    CONT RES 1
    KEY1 EQU .0 ; PINO RC0
    KEY2 EQU .1 ; PINO RC1
    AUX1 RES 1
    AUX2 RES 1
    
RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START                   ; go to beginning of program

; TODO ADD INTERRUPTS HERE IF USED

MAIN_PROG CODE                      ; let linker place main program

START
    CLRF CONT		;INICIALIZANDO CONT1 COM 0
    CLRF AUX1		;INICIALIZANDO AUX1 COM 0
    CLRF AUX2		;INICIALIZANDO AUX2 COM 0
    
    CLRF TRISD		;TORNANDO A PORTD COMO SAÍDA
    BSF TRISC, KEY1	;CONFIGURANDO KEY1 COMO PORTA DE ENTRADA
    BSF TRISC, KEY2	;CONFIGURANDO KEY2 COMO PORTA DE ENTRADA
    CLRF PORTD		;COLOCANDO ZER0 EM TODOS OS PINOS DE PORTD
   
LOOP
    BTFSC PORTC, KEY1   ;VERIFICA SE KEY1 ESTÁ DESATIVADA, SE SIM PULA UMA INSTRUÇÃO
    BRA LOOPA           ;DESVIO PARA O LOOPA
    BRA LOOPB		;DESVIO PARA O LOOPB
    
    LOOPA
    BTFSC PORTC, KEY2   ;VERIFICA SE KEY2 ESTÁ DESATIVADA, SE SIM PULA UMA INSTRUÇÃO
    BRA LOOPC	;DESVIO PARA O LOOPC
    BRA LOOPD	;DESVIO PARA O LOOPD
	
    LOOPB
    BTFSC PORTC, KEY2   ;VERIFICA SE KEY2 ESTÁ DESATIVADA, SE SIM PULA UMA INSTRUÇÃO
    BRA LOOPE	;DESVIO PARA O LOOPE
    BRA LOOPF	;DESVIO PARA O LOOPF
    
    LOOPC
    GOTO LOOP	;DESVIO PARA O LOOP

    LOOPD
    CALL INCREMENT	;CHAMA A ROTINA DE INCREMENTO
    GOTO LOOP	;DESVIO PARA O LOOP
	
    LOOPE
    CALL DECREMENT	;CHAMA A ROYINA DE DESCREMENTO
    GOTO LOOP	;DESVIO PARA O LOOP

    LOOPF
    GOTO LOOP	;DESVIO PARA O LOOP
	
INCREMENT
    CALL ATRASO_500ms
    CALL ATRASO_500ms
    BTFSC PORTC, KEY1
    INCF CONT
    MOVFF CONT, PORTD  ;MOVENDO CONT PARA O PORTD
    RETURN
    
DECREMENT
    CALL ATRASO_500ms
    CALL ATRASO_500ms
    BTFSC PORTC, KEY2
    DECF CONT
    MOVFF CONT, PORTD	;MOVENDO CONT PARA O PORTD
    RETURN
    
ATRASO_2ms ; Subrotina que gera atraso de 2 ms
    MOVLW .152
    MOVWF AUX2 ; Carrega contador para 200 interações
REPETE2      ; Inicio do loop    
    NOP      ; 10 NOPs -> 10 us
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    DECFSZ AUX2
    GOTO REPETE2  ; Repete interações até que CONTA2 = 0
    RETURN

ATRASO_500ms ; Subrotina que gera atraso de 500 ms
    MOVLW .250
    MOVWF AUX1 ; Carrega contador para 250 interações
REPETE_500   ; Inicio d92o loop
    CALL ATRASO_2ms ; Espera 2 ms
    DECFSZ AUX1
    GOTO REPETE_500 ; Repete interações até que CONTA500 = 0
    RETURN
 
    END
    